POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VSCode rest client is",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/2

###
PUT http://localhost:3001/api/notes/2
Content-Type: application/json

{
    "content": "Hello universe",
    "important": true
}